// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'about': string;
  'connect': string;
  'inner': string;
  'role': string;
}
export const cssExports: CssExports;
export default cssExports;
