// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inner': string;
  'splash': string;
}
export const cssExports: CssExports;
export default cssExports;
